version: "3"

services:

  varnish:
    image: varnish
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: ${RESTART}
    networks:
      - network

networks:

  network:
    external:
      name: ${NETWORK}
